//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.ServiceReferenceCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalc.IServiceCalculator")]
    public interface IServiceCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/SumNumbers", ReplyAction="http://tempuri.org/IServiceCalculator/SumNumbersResponse")]
        long SumNumbers(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/SumNumbers", ReplyAction="http://tempuri.org/IServiceCalculator/SumNumbersResponse")]
        System.Threading.Tasks.Task<long> SumNumbersAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/DivideNumbers", ReplyAction="http://tempuri.org/IServiceCalculator/DivideNumbersResponse")]
        double DivideNumbers(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/DivideNumbers", ReplyAction="http://tempuri.org/IServiceCalculator/DivideNumbersResponse")]
        System.Threading.Tasks.Task<double> DivideNumbersAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCalculatorChannel : CalculatorClient.ServiceReferenceCalc.IServiceCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCalculatorClient : System.ServiceModel.ClientBase<CalculatorClient.ServiceReferenceCalc.IServiceCalculator>, CalculatorClient.ServiceReferenceCalc.IServiceCalculator {
        
        public ServiceCalculatorClient() {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long SumNumbers(int a, int b) {
            return base.Channel.SumNumbers(a, b);
        }
        
        public System.Threading.Tasks.Task<long> SumNumbersAsync(int a, int b) {
            return base.Channel.SumNumbersAsync(a, b);
        }
        
        public double DivideNumbers(int a, int b) {
            return base.Channel.DivideNumbers(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DivideNumbersAsync(int a, int b) {
            return base.Channel.DivideNumbersAsync(a, b);
        }
    }
}
